version: "2"

services:
  website:
    container_name: my_service
    build: .
    command: >
      uvicorn
      --host 0.0.0.0
      --port 8000
      --reload
      "main:app"
    volumes:
      - "./app:/app"
    ports:
      - "8000:8000"
    depends_on:
      - db
    
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=my_db
  
volumes:
  postgres_data: